ProjectPRN/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Google;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using ProjectPRN.Models;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;
using ProjectPRN.Utils;
using ProjectPRN.Data;

namespace ProjectPRN.Controllers
{
    public class LoginController : Controller
    {
        private readonly AppDBContext _dbContext;
        public LoginController(AppDBContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(string email, string password)
        {
            var user = _dbContext.User.FirstOrDefault(u => u.Email == email && u.Password == password);
            if (user != null)
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, user.Name),
                    new Claim(ClaimTypes.Email, user.Email),
                };
                var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                var authProperties = new AuthenticationProperties
                {
                };
                await HttpContext.SignInAsync(
                    CookieAuthenticationDefaults.AuthenticationScheme,
                    new ClaimsPrincipal(claimsIdentity),
                    authProperties);
                SaveUserId.AddToSession(HttpContext,"UserId",user.ID);
                if (user.Role > 1)
                {
                    return Redirect("/admin/dashboards/index");
                }
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.ErrorMessage = "Invalid email or password.";
                return View("Index");
            }
        }

        public async Task LoginWithGoogle()
        {
            await HttpContext.ChallengeAsync(GoogleDefaults.AuthenticationScheme,
                new AuthenticationProperties
                {
                    RedirectUri = Url.Action("GoogleResponse")
                });
        }
        public async Task<IActionResult> GoogleResponse()
        {
            var result = await HttpContext.AuthenticateAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            var claims = result.Principal.Identities.FirstOrDefault().Claims.Select(claim => new
            {
                claim.Issuer,
                claim.OriginalIssuer,
                claim.Type,
                claim.Value
            }).ToList();
            var email = claims?.FirstOrDefault(x => x.Type == ClaimTypes.Email)?.Value;
            var name = claims?.FirstOrDefault(x => x.Type == ClaimTypes.Name)?.Value;
            if (!string.IsNullOrEmpty(email))
            {
                Save(email, name);
            }
            return RedirectToAction("Index", "Home", new { area = "" });
        }
        private void Save(string email, string name)
        {
            var user = _dbContext.User.FirstOrDefault(u => u.Email == email);
            if (user == null) 
            {
                user = new User
                {
                    Email = email,
                    Name = name,
                    Password = email,
                    Role = 1,
                };
                _dbContext.User.Add(user);
            }
            _dbContext.SaveChanges(); 
        }
    }
}

ProjectPRN/Controllers/SignUpController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjectPRN.Data;
using ProjectPRN.Models;

namespace ProjectPRN.Controllers
{
    public class SignUpController : Controller
    {
        private readonly AppDBContext _dbContext;
        public SignUpController(AppDBContext dbContext)
        {
            _dbContext = dbContext;
        }
        [HttpGet] 
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost] 
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SignUp(User user)
        {
            if (ModelState.IsValid)
            {
                user.Role = 1;
                _dbContext.Add(user);
                await _dbContext.SaveChangesAsync();

                return RedirectToAction("Index", "Login"); 
            }
            return RedirectToAction("Index",user);
        }
    }
}

ProjectPRN/Views/Login/Index.cshtml
<style>
    body {
        margin: 0;
        padding: 0;
    /*     background: url('https://scontent.xx.fbcdn.net/v/t1.15752-9/430974474_437096188661862_958657358504182726_n.png?stp=dst-png_p403x403&_nc_cat=101&ccb=1-7&_nc_sid=5f2048&_nc_eui2=AeHHqZc-zrJgYTlHkatb4Pz7lEI4gen4t6GUQjiB6fi3oW9y6-930-UuRQRVtLAl5wbRXxhA6ii6Ogj5fXTQTnI2&_nc_ohc=RAR3_V1J6I8AX9o3ETr&_nc_ad=z-m&_nc_cid=0&_nc_ht=scontent.xx&oh=03_AdQq9fnFcyXFdNq7Q9ET2wWhAL7OkIXxevDxuHiz4Ae-YQ&oe=66248994') no-repeat center center fixed; */
        background-size: cover;
        font-family: Arial, sans-serif;
    }

    .user-card {
        width: 350px;
        margin: 5% auto;
        background: #FBFBFB;
        overflow: hidden;
        box-shadow: 0 1px 3px rgba(0,0,0,0.08);
        border-radius: 5px;
    }

    .login-box, .signup-box {
        padding: 20px;
        background: #FBFBFB;
    }

    .form-control {
        width: 100%;
        height: 40px;
        margin: 6px 0;
        padding: 3px 12px;
        border: 1px solid #dee3e4;
        border-radius: 3px;
    }

    .btn-primary {
        width: 100%;
        background: #03b3b5;
        color: #fff;
        border: none;
        margin-top: 10px;
        padding: 10px;
    }

    .login-with-google {
        display: block;
        width: 100%;
        background: #DB4A37;
        color: #fff;
        text-align: center;
        padding: 10px;
        margin-top: 15px;
        border-radius: 3px;
        text-decoration: none;
    }
        .login-with-google .fa-brands {
            float: left;
            font-size: 21px;
            width: 50px;
            height: 26px;
            padding: 2px;
            text-align: center;
            border-right: 1px solid #fff;
        }

    .footer {
        text-align: center;
        color: #666;
        font-size: 13px;
        padding: 10px;
    }

</style>
<div class="user-card">
    <div class="login-box">
        <h1 class="text-center">Login</h1>
        <br />
        <form asp-controller="Login" asp-action="Login" method="post" class="d-grid gap-2">
            <input type="email" name="email" class="form-control" placeholder="Enter Email " />
            <input type="password" name="password" class="form-control" placeholder="Enter Password" />
            <br />
            <input type="submit" name="login" value="Login" class="btn btn-primary" />
        </form>
        <div class="or text-center" style="margin-top:15px;">OR</div>
        <a asp-controller="Login" asp-action="LoginWithGoogle" class="login-with-google">
            <i class="fa-brands fa-google" ></i>
            Continue with Gmail
        </a>
    </div>
    <div class="footer">
        <span>or </span><a asp-controller="SignUp" asp-action="Index">Sign Up</a>
    </div>
</div>